package com.model;
// Generated Feb 18, 2018 9:05:49 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Animals generated by hbm2java
 */
@Entity
@Table(name = "animals", catalog = "websystique")
public class Animals implements java.io.Serializable {

	private Integer id;
	private String name;

	public Animals() {
	
	
	
	
	
	}

	public Animals(String name) {
	//	this.name = name;
	
	
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
